#!/bin/sh

SRCS=$(git diff --cached --name-only --diff-filter=ACM --no-color | grep --color=never -e '\.py$')
#set -x

[ -z "${SRCS}" ] && exit 0

echo flake8
flake8 ${SRCS}
if [ $? != 0 ]; then
	echo "Code fails pyflake check."
	exit 1
fi

echo pylint
pylint ${SRCS}
if [ $? != 0 ]; then
	echo "Code fails pylint py3k check. Please check the code in order to improve the quality."
fi


echo "Running tests..."
pytest --cov=helixa_app tests/
code=$?

if [ "$code" -eq "0" ]; then
    echo "All tests passed. Committing..."

  else
      echo "Please (re)check tests! :("
      exit 1
  fi;
