version: '3'

services:
  redis:
    build:
      context: .
      dockerfile: ./docker/Dockerfile_redis
    container_name: redis
    ports:
      - 6379:6379
    volumes:
      - ./helixa_app/conf/redis.conf:/usr/local/etc/redis/redis.conf

  mongo_db:
    build:
      image: bitnami/mongodb:latest
    container_name: mongo_db
    ports:
      - 27017:27017
    volumes:
      - ./docker/mongo_db_storage:/bitnami

  helixa_app:
    container_name: helixa_app
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    environment:
      - HELIXA_APP_CONFIG=/app/helixa_app/conf/dev.ini
      - LOG_PATH=/app/logs
      - LOG_LEVEL=DEBUG
      - LOG_CONF=/app/helixa_app/conf/log_config/log_config.ini
      - REDIS_HOST_ADDRESS=127.0.0.1
      - REDIS_PORT_BIND=6379
      - USE_REDIS_CACHE=true
      - DATABASE_CONNECTION=relational_db:///helixa_app_dev.db
    tty: true
    stdin_open: true
    volumes:
      - ./helixa_app:/app/helixa_app
      - ./tests:/app/tests
      - ./logs:/app/logs
      - ./.bumpversion.cfg:/app/.bumpversion.cfg
      - ./categories.json:/app/categories.json
      - ./psychographics.json:/app/psychographics.json
    ports:
      - 5000:5000
    depends_on:
      - redis
      - mongo_db
